language: node_js
# sudo: false
node_js:
  - '6.9.2'

env: BROWSERS=firefox E2E_BROWSERS=Firefox

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - npm install -g bower
  - bower install

install: npm install

script: npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov --file coverage/lcov.info --disable search